Migrate off of the legacy pre-1.14 recording rules
SumoLogic/sumologic-kubernetes-collection pull request #1030
Opened 2020-10-21 20:42 UTC by vsinghal13

###### Description
- Removed the flag `kubeTargetVersionOverride: 1.13.0-0`
- following node rule metrics have been removed in from 1.14, so we have to add them to our values file.

| Metrics                                      	|
|----------------------------------------------	|
| :node_cpu_saturation_load1:                  	|
| :node_cpu_utilisation:avg1m                  	|
| :node_disk_saturation:avg_irate              	|
| :node_disk_utilisation:avg_irate             	|
| :node_memory_swap_io_bytes:sum_rate          	|
| :node_memory_utilisation:                    	|
| :node_net_saturation:sum_irate               	|
| :node_net_utilisation:sum_irate              	|
| node:cluster_cpu_utilisation:ratio           	|
| node:cluster_memory_utilisation:ratio        	|
| node:node_cpu_saturation_load1:              	|
| node:node_cpu_utilisation:avg1m              	|
| node:node_disk_saturation:avg_irate          	|
| node:node_disk_utilisation:avg_irate         	|
| node:node_filesystem_avail:                  	|
| node:node_filesystem_usage:                  	|
| node:node_inodes_free:                       	|
| node:node_inodes_total:                      	|
| node:node_memory_bytes_total:sum             	|
| node:node_memory_swap_io_bytes:sum_rate      	|
| node:node_memory_utilisation:                	|
| node:node_memory_utilisation:ratio           	|
| node:node_memory_utilisation_2:              	|
| node:node_net_saturation:sum_irate           	|
| node:node_net_utilisation:sum_irate          	|

- following `apiserver` and `kube-scheduler` have been replaced/renamed in 1.14

| Pre-1.14 apiserver and kube-scheduler recording rules 	| Post-1.14 apiserver and kube-scheduler recording rules 	|
|:-:	|:-:	|
| cluster_quantile:apiserver_request_latencies:histogram_quantile 	| cluster_quantile:apiserver_request_duration_seconds:histogram_quantile 	|
| cluster_quantile:scheduler_binding_latency:histogram_quantile 	| cluster_quantile:scheduler_binding_duration_seconds:histogram_quantile 	|
| cluster_quantile:scheduler_e2e_scheduling_latency:histogram_quantile 	| cluster_quantile:scheduler_e2e_scheduling_duration_seconds:histogram_quantile 	|
| cluster_quantile:scheduler_scheduling_algorithm_latency:histogram_quantile 	| cluster_quantile:scheduler_scheduling_algorithm_duration_seconds:histogram_quantile 	|
###### Testing performed

- [ ] ci/build.sh
- [ ] Redeploy fluentd and fluentd-events pods
- [ ] Confirm events, logs, and metrics are coming in

2020-10-22 09:16 UTC, sumo-drosiek approved these changes

2020-10-28 09:21 UTC, perk-sumo reviewed
Why we add `pre-1.14-node-rules` in here and not calculate this on the Sumo backend if needed?

2020-11-10 09:42 UTC, sumo-drosiek requested changes
Remove auto-generated files due to #1052

2020-11-16 15:28 UTC, frankreno approved these changes
LGTM

2020-11-30 15:27 UTC, sumo-drosiek approved these changes
Looks OK

2020-11-30 15:44 UTC, merged

2020-12-14 17:28 UTC, perk-sumo commented
Migration script PR: https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1216