Update autoscaling/v1 to autoscaling/v2beta2
SumoLogic/sumologic-kubernetes-collection pull request #1071
Opened 2020-11-06 13:32 UTC by pmalek-sumo

###### Description

Update autoscaling/v1 to autoscaling/v2beta2 in order to enable custom metrics autoscaling and autoscaling based on memory utilization.

ref: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/#autoscaling-on-multiple-metrics-and-custom-metrics

###### Testing performed

- [ ] ci/build.sh
- [ ] Redeploy fluentd and fluentd-events pods
- [ ] Confirm events, logs, and metrics are coming in

2020-11-06 13:45 UTC, sumo-drosiek commented
@frankreno @perk-sumo 
Do we want to support more factors than CPU? IMHO, we should avoid to copy k8s templates to values.yaml if it's possible

2020-11-06 15:56 UTC, frankreno commented
I agree with @sumo-drosiek.  I feel like we should be able to handle this w/o a breaking change as well. In the values.yaml we can have the same key we do today (`targetCPUUtilizationPercentage`).  We can modify the HPA with new format in the template as opposed to the values.  If customers want to add more metrucs, we can add an `extraHPAMetrics` property that the template could render no?

2020-11-06 16:01 UTC, pmalek-sumo commented
> I agree with @sumo-drosiek. I feel like we should be able to handle this w/o a breaking change as well. In the values.yaml we can have the same key we do today (`targetCPUUtilizationPercentage`). We can modify the HPA with new format in the template as opposed to the values. If customers want to add more metrucs, we can add an `extraHPAMetrics` property that the template could render no?

@frankreno 

The reason I'm hesitant on this approach is that

* we would be "overriding" the "scope" (?) of `targetCPUUtilizationPercentage` (`v1` vs `v2beta`) - this in itself wouldn't be that big of a deal
* we already had a thread on slack about a customer who'd like to configure hpa based on memory, this will require either `extraHPAMetrics` as suggested or something like `targetMemoryUtilizationPercentage` which doesn't exist neither in `v1` nor  in `v2beta2` which might confuse users 

Not my call, just chippin' in :)

2020-11-06 16:05 UTC, perk-sumo commented
There is one problem with doing a breaking change and fully migrating - it's still a `beta` version.
I'd rather have some "scope" inconsistence than changing our configuration back and forth in case the hpa api changes.

2020-11-06 16:16 UTC, pmalek-sumo commented
> There is one problem with doing a breaking change and fully migrating - it's still a `beta` version.
> I'd rather have some "scope" inconsistence than changing our configuration back and forth in case the hpa api changes.

Ok, sure. Let's do that then.
One thing though: do we set the default and if so then what value do we want for `targetMemoryUtilizationPercentage`?

2020-11-09 11:46 UTC, perk-sumo commented
Let's set it at 50% but not use it by default.

2020-11-09 11:47 UTC, perk-sumo commented on deploy/helm/sumologic/values.yaml
> -      targetCPUUtilizationPercentage: 50
Let's not change this key just yet (as long as autoscaling `v2` is in beta)

2020-11-09 11:48 UTC, perk-sumo requested changes
Let's not change the `values.yaml` keys around autoscaling just yet.

2020-11-09 15:56 UTC, pmalek-sumo commented
Removing `breaking-change` label as we decided to use `targetMemoryUtilizationPercentage` key for autoscaling based on memory utilization

2020-11-12 16:15 UTC, pmalek-sumo commented
@perk-sumo Please take a look one more time

2020-11-13 08:25 UTC, sumo-drosiek approved these changes

2020-11-13 09:12 UTC, perk-sumo approved these changes
👍

2020-11-13 09:13 UTC, merged