fix(helm): add job and cronjob to clusterrole's permission set
SumoLogic/sumologic-kubernetes-collection pull request #1983
Opened 2021-12-14 15:14 UTC by pmalek-sumo

2021-12-14 15:42 UTC, swiatekm-sumo approved these changes

2021-12-14 16:48 UTC, perk-sumo requested changes
Overall I'm 👍 but please update the changelog :)

2021-12-15 11:48 UTC, pmalek-sumo commented
@perk-sumo PTAL, added the changelog.

2021-12-17 09:33 UTC, perk-sumo approved these changes
🚀

2021-12-17 09:33 UTC, merged