chore: add warning for increased cpu limit for Fluentds
SumoLogic/sumologic-kubernetes-collection pull request #2108
Opened 2022-02-10 11:43 UTC by perk-sumo

HPA looks at request CPU for scaling.
Fluentd reaches 1 core at max.

So when CPU limit is set to `3` (or `3000m`) with HPA's `targetCPUUtilizationPercentage: 50` means that HPA aims to get every Fluentd to 1.5 core utilization which won't happen.
Hence it will not scale it out.

CPU limit for Fluentd should be always `1000m` at max.

2022-02-10 11:51 UTC, pmalek-sumo commented
I'm not sure if comment is enough. How about adding a section to docs? Performance or best practices?

2022-02-10 12:05 UTC, pmalek-sumo requested changes

2022-02-10 12:05 UTC, pmalek-sumo commented on deploy/docs/Best_Practices.md
> +When enabling the Fluentd Autoscaling please make sure to not set Fluentd's CPU limit above `1000m` as that will
```suggestion
When enabling the Fluentd Autoscaling please make sure to not set Fluentd's CPU request above `1000m` as that will
```

2022-02-11 08:57 UTC, perk-sumo commented on deploy/docs/Best_Practices.md
> +break the autoscaling. The reason for that is Fluentd can use 1 CPU core at max.
Good point, I've added that info.

2022-02-11 09:04 UTC, pmalek-sumo approved these changes

2022-02-11 09:04 UTC, merged