[Backport-v2] Added imagePullSecrets field in otel events and Sumologic-setup template
SumoLogic/sumologic-kubernetes-collection pull request #2705
Opened 2022-12-15 11:18 UTC by swiatekm-sumo

Backport of #2689 to v2

2022-12-15 11:27 UTC, astencel-sumo commented on deploy/helm/sumologic/templates/setup/job.yaml
> +        imagePullSecrets: {{ .Values.sumologic.setup.job.image.pullSecrets }}
What about this? https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/v2.19.0/deploy/docs/Working_with_container_registries.md?plain=1#L46

2022-12-15 11:27 UTC, astencel-sumo requested changes
The setup job already has this

2022-12-15 11:30 UTC, astencel-sumo commented on deploy/helm/sumologic/templates/events/otelcol/statefulset.yaml
> +        imagePullSecrets:
Doesn't `otelevents` already use the `sumologic.pullSecrets` by using the common service account?

2022-12-21 10:00 UTC, swiatekm-sumo commented
Reverting the original change in https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/2721 and closing this.

2022-12-21 10:00 UTC, closed without merging