docs(prometheus): Added a section on prometheus sharding
SumoLogic/sumologic-kubernetes-collection pull request #3140
Opened 2023-07-07 19:46 UTC by rnishtala-sumo

### Checklist

- [ ] Changelog updated or skip changelog label added
- [ ] Documentation updated
- [ ] Template tests added for new features
- [ ] Integration tests added or modified for major features

2023-07-10 14:50 UTC, sumo-drosiek approved these changes

2023-07-12 14:40 UTC, swiatekm-sumo requested changes
We should mention that this will cause recording rule metrics which require global aggregations to stop working - and with them, possibly the Kubernetes App.

2023-07-13 07:27 UTC, kkujawa-sumo approved these changes

2023-07-13 15:13 UTC, swiatekm-sumo approved these changes

2023-07-13 15:18 UTC, merged