feat: Check if remote write definitions are present when Prometheus i…
SumoLogic/sumologic-kubernetes-collection pull request #3600
Opened 2024-03-14 21:48 UTC by dmolenda-sumo

…s not enabled

2024-03-18 05:45 UTC, sumo-drosiek approved these changes

2024-03-18 10:48 UTC, swiatekm-sumo requested changes
Can we add a Go test for this as well, checking all the possible config value combinations?

2024-03-27 20:24 UTC, dmolenda-sumo commented
> Can we add a Go test for this as well, checking all the possible config value combinations?

If there is any other combination that should be tested, please let me know

2024-03-28 08:48 UTC, swiatekm-sumo approved these changes

2024-03-28 10:06 UTC, merged