Don't scrape from headless services
SumoLogic/sumologic-kubernetes-collection pull request #895
Opened 2020-09-09 16:07 UTC by pmalek-sumo

###### Description

This prevents prometheus double scraping fluentd pods by removing the annotations from headless services.

###### Testing performed

- [ ] ci/build.sh
- [ ] Redeploy fluentd and fluentd-events pods
- [ ] Confirm events, logs, and metrics are coming in

2020-09-09 16:07 UTC, pmalek-sumo commented
Fixes https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/776

2020-09-09 16:12 UTC, sumo-drosiek reviewed
I think thats the correct solution. We could eventually add additional label for scraping metrics
@perk thoughts?

2020-09-10 08:29 UTC, perk-sumo commented
Yeah, I think that works for now but let's fix it properly in `2.0`: https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/896

2020-09-10 08:29 UTC, perk-sumo approved these changes

2020-09-10 18:57 UTC, vsinghal13 approved these changes

2020-09-10 18:58 UTC, vsinghal13 commented
If we change the labels now, will it be considered a breaking change?

2020-09-10 23:18 UTC, frankreno approved these changes
LGTM

2020-09-11 07:01 UTC, sumo-drosiek requested changes
Valid point from @vsinghal13 
@pmalek-sumo could you verify that?

2020-09-11 08:30 UTC, sumo-drosiek approved these changes
Verified, no need for `--force` and change is not considered as breaking change

2020-09-11 15:02 UTC, merged