Introduce cache refresh variation
SumoLogic/sumologic-kubernetes-collection pull request #952
Opened 2020-09-25 08:46 UTC by astencel-sumo

###### Description

This PR introduces a random variation in cache refresh interval for each pod, allowing the load on API server to be spread in time.

By default, there are multiple Fluentd pods running in a cluster, each of the pods maintaining its own version of pod metadata cache. The cache is being refreshed by each Fluentd pod independently in regular intervals specified by the `fluentd.metadata.cacheRefresh` configuration variable. Before this change, the cache refresh interval was equal for all pods, causing all of them to flood API server with queries in approximately the same time.

The introduction of `fluentd.metadata.cacheRefreshVariationRange` configuration variable makes it possible to spread the load on API server by changing the cache refresh interval by a different, randomly assigned value for each pod. For example, if the `cacheRefresh` value is 1 hour and `cacheRefreshVariationRange` is 30 minutes, the actual cache refresh interval for each pod will vary between 45 minutes and 1 hour 15 minutes.

###### Testing performed

- [x] ci/build.sh
- [ ] Redeploy fluentd and fluentd-events pods
- [ ] Confirm events, logs, and metrics are coming in

2020-09-25 10:38 UTC, sumo-drosiek requested changes
Could we change name to `cache refresh variation` (without `range`) ?

2020-09-25 11:59 UTC, perk-sumo approved these changes
I'm 👍  except for the `variationRange` -> `variation` rename.

2020-09-25 12:56 UTC, perk-sumo requested changes
Let's change the `variationRange` into `variation` in the code as well co that 30min variation means +/- 30min and not +/- 15min

2020-09-25 14:58 UTC, perk-sumo commented on deploy/helm/sumologic/README.md
> +`fluentd.metadata.cacheRefreshVariation` | Option to control the variation in seconds by which the cacheRefresh option is changed for each pod separately. For example, if cache refresh is 1 hour and
```suggestion
`fluentd.metadata.cacheRefreshVariation` | Option to control the variation in seconds by which the cacheRefresh option is changed for each pod separately. For example, if cache refresh is 1 hour and variation is 15 minutes, then actual cache refresh interval will be a random value between 45 minutes and 1 hour 15 minutes, different for each pod. This helps spread the load on API server that the cache refresh induces. Setting this to 0 disables cache refresh variation. | `900`
```

2020-09-25 15:02 UTC, perk-sumo approved these changes
LGTM but please squash :)

2020-09-25 19:47 UTC, vsinghal13 approved these changes

2020-09-28 09:57 UTC, sumo-drosiek approved these changes

2020-09-28 10:13 UTC, merged